<?php
namespace Database\Seeders;
use App\Models\AccionCompromiso;use App\Models\Comunidad;use Illuminate\Database\Seeder;
class AccionCompromisoSeeder extends Seeder{public function run():void{$ids=Comunidad::pluck('id','nombre');$rows=[
['Mejoramiento de caminos en la red departamental','Ejecutar trabajos de mejoramiento y mantenimiento vial.','Caminos y Accesibilidad','alta',null],
['Refacción del cuatriciclo de la posta de San José','Reacondicionar y poner nuevamente en funcionamiento el vehículo de salud.','Salud','alta','San José'],
['Dotación de heladera al Centro de Salud de Pampa Grande','Dotar al centro de salud de una heladera operativa.','Salud','alta','Pampa Grande'],
['Refacción de la Unidad Educativa de Volcán Blanco','Ejecutar trabajos de refacción y mejoramiento de infraestructura educativa.','Educación','alta','Volcán Blanco'],
['Dotación de semillas para productores de Motoví','Gestionar semillas para fortalecer la producción.','Producción y Comercialización','alta','Motoví'],
['Asignación efectiva de 3 ítems de salud para Tariquía','Dar continuidad a la gestión de tres ítems de salud.','Salud','alta',null],
['Gestionar y disponer de una ambulancia para Tariquía','Gestionar una ambulancia para fortalecer la atención.','Salud','alta',null],
['Agilizar la conclusión del proyecto de electrificación','Impulsar gestiones institucionales para concluir el proyecto.','Energía','alta',null],
['Reparación y reposición de paneles solares y baterías','Reparar o sustituir paneles solares y baterías deterioradas.','Energía','alta',null],
['Revisión de restricciones para la apertura de caminos','Revisar restricciones legales, ambientales e institucionales.','Caminos y Accesibilidad','alta',null],
['Instalación de medidores eléctricos en unidades educativas','Gestionar la instalación de medidores eléctricos.','Energía','alta',null],
['Incorporación de la miel de Tariquía a programas alimentarios','Evaluar la incorporación de miel producida en Tariquía.','Producción y Comercialización','media',null],
['Implementación de veterinaria móvil para Tariquía','Diseñar e implementar un servicio veterinario móvil.','Producción y Comercialización','media',null],
['Formulación del proyecto de nueva Unidad Educativa','Desarrollar un proyecto para nueva infraestructura educativa.','Educación','media',null],
['Incorporación de Chillaguatas a la Red Departamental','Dar seguimiento a la propuesta de incorporación.','Caminos y Accesibilidad','media','Chillaguatas'],
['Refacción y puesta en funcionamiento de maquinaria','Refaccionar maquinaria para atender mantenimiento vial.','Caminos y Accesibilidad','media',null],
['Mejoramiento del tramo vial Chalamarca-La Cumbre','Ejecutar acciones de mejoramiento vial.','Caminos y Accesibilidad','alta','Chiquiacá Norte'],
['Mejoramiento del tramo La Cumbre - Pampa Grande','Gestionar el mejoramiento del tramo vial.','Caminos y Accesibilidad','alta','Pampa Grande'],
['Gestión de maquinaria, combustible y repuestos','Fortalecer la capacidad operativa para mantenimiento vial.','Caminos y Accesibilidad','alta','Salinas'],
['Evaluación de obras de arte y pasos críticos en caminos','Identificar puntos críticos que requieren puentes y alcantarillas.','Caminos y Accesibilidad','media','Loma Alta'],
['Incorporación de comunidades prioritarias a planificación vial','Gestionar la consideración de comunidades prioritarias.','Caminos y Accesibilidad','media','Chillaguatas'],
['Fortalecimiento de atención médica en comunidades','Mejorar la cobertura y capacidad de atención de salud.','Salud','alta','Pampa Redonda'],
['Dotación de medicamentos e insumos para establecimientos','Garantizar disponibilidad de medicamentos e insumos.','Salud','alta','Salinas'],
['Evaluación de necesidad de laboratorio y servicios complementarios','Analizar la necesidad de fortalecer servicios sanitarios.','Salud','media','Salinas'],
['Mejoramiento de sistemas de agua potable comunitarios','Fortalecer sistemas de abastecimiento de agua.','Agua','alta','Chajllas'],
['Fortalecimiento de sistemas de microriego','Evaluar y mejorar sistemas de riego para la producción.','Agua','media','El Cajón'],
['Fortalecimiento de producción apícola y cadena de valor','Impulsar producción, transformación y comercialización.','Producción y Comercialización','alta','Piedra Grande'],
['Construcción de estrategia de comercialización','Desarrollar mecanismos de venta y posicionamiento.','Producción y Comercialización','media','Chiquiacá Sur'],
['Fortalecimiento sanitario y productivo de ganadería','Brindar apoyo técnico para mejorar la producción ganadera.','Producción y Comercialización','media','La Misión'],
['Diseño de propuesta de turismo comunitario Tariquía','Construir una propuesta turística basada en naturaleza y comunidad.','Turismo','alta','Río Conchas'],
['Desarrollo de Marca Territorial Tariquía','Crear una identidad territorial para productos y turismo.','Turismo','alta','La Planchada'],
['Elaborar nuevo plan de manejo de la reserva',null,'Medio Ambiente','alta','Chiquiacá Norte']];
foreach($rows as [$titulo,$descripcion,$area,$prioridad,$comunidad])AccionCompromiso::updateOrCreate(['titulo'=>$titulo],['descripcion'=>$descripcion,'area'=>$area,'prioridad'=>$prioridad,'comunidad_id'=>$comunidad?($ids[$comunidad]??null):null,'estado'=>'identificado','porcentaje'=>0]);}}