<x-app-layout>
<x-slot name="header"><div><p class="text-sm font-semibold text-emerald-700">{{ auth()->check() ? 'Panel ejecutivo' : 'Información territorial' }}</p><h2 class="font-extrabold text-2xl text-slate-900">{{ auth()->check() ? 'Bienvenido, '.Auth::user()->name : 'Monitoreo de Tariquía' }}</h2><p class="text-sm text-slate-500 mt-1">Seguimiento territorial de Tariquía</p></div></x-slot>
<div class="py-6"><div class="max-w-7xl mx-auto px-4 space-y-6">
<section class="ui-card p-5 w-full"><div class="flex flex-wrap justify-between gap-3 mb-4"><div><h3 class="font-bold text-lg">Mapa territorial interactivo</h3><p class="text-sm text-slate-500">Seleccione una comunidad para consultar toda su información</p></div><div class="flex flex-wrap gap-2"><input id="map-search" type="search" placeholder="Buscar comunidad..." class="text-sm"><select id="territory-filter" class="text-sm"><option value="">Todos los territorios</option>@foreach($porTerritorio as $territorio=>$total)<option value="{{ $territorio }}">{{ $territorio }} ({{ $total }})</option>@endforeach</select></div></div><div id="map"></div></section>

<div class="kpi-grid">@foreach([['Comunidades',$stats['comunidades'],'emerald'],['Necesidades',$stats['necesidades'],'amber'],['Compromisos',$stats['compromisos'],'indigo'],['Acciones',$stats['acciones'],'blue'],['Responsables',$stats['responsables'],'violet']] as [$label,$value,$color])<div class="ui-card ui-card-hover p-5 border-t-4 border-{{ $color }}-500"><p class="text-sm font-semibold text-slate-500">{{ $label }}</p><p class="text-3xl font-extrabold text-slate-900 mt-1">{{ $value }}</p></div>@endforeach</div>

@auth<section class="ui-card overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h3 class="font-bold text-lg text-red-800">Responsables con acciones retrasadas</h3><p class="text-sm text-slate-500">Acciones que superaron su fecha lÃ­mite y aÃºn no estÃ¡n completadas.</p></div><a href="{{ route('reportes.alertas') }}" class="ui-btn-danger">Ver detalle</a></div><div class="divide-y">@forelse($incumplimientosPorResponsable as $incumplimiento)<div class="grid gap-2 p-4 text-sm md:grid-cols-4"><b>{{ $incumplimiento['responsable'] }}</b><span>{{ $incumplimiento['accion'] }}</span><span>{{ ucfirst(str_replace('_',' ',$incumplimiento['estado'])) }}</span><strong class="text-red-700">{{ $incumplimiento['dias'] }} dÃ­a(s) de retraso</strong></div>@empty<p class="p-5 text-sm text-emerald-700">No existen acciones vencidas pendientes.</p>@endforelse</div></section>@endauth

@auth<section class="ui-card p-5 w-full"><div class="flex justify-between items-center"><div><h3 class="font-bold text-lg">Próximos vencimientos</h3><p class="text-sm text-slate-500">Acciones que requieren atención prioritaria</p></div><span class="ui-badge bg-red-50 text-red-700">{{ $stats['bloqueadas'] }} bloqueadas</span></div><div class="mt-4 upcoming-grid">@forelse($proximas as $a)<a href="{{ route('compromisos.show',$a->accion_compromiso_id) }}" class="block p-4 border rounded-xl hover:bg-slate-50 transition"><div class="flex justify-between gap-2"><b class="text-sm">{{ $a->titulo }}</b><span class="text-xs text-slate-500 whitespace-nowrap">{{ $a->fecha_limite->format('d/m/Y') }}</span></div><p class="text-xs text-slate-500 mt-2">{{ $a->compromiso?->comunidad?->nombre }} · {{ $a->responsable?->nombre_completo??'Sin responsable' }}</p></a>@empty<p class="text-slate-500 text-sm">No hay fechas límite registradas.</p>@endforelse</div></section>@endauth

@auth
<section class="ui-card p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-bold text-lg">Estado del monitoreo</h3><p class="text-sm text-slate-500">Situaciones que requieren revisión</p></div><a href="{{ route('reportes.alertas') }}" class="ui-btn-primary">Revisar alertas</a></div><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-red-50 p-4"><p class="text-sm font-semibold text-red-700">Acciones vencidas</p><p class="text-3xl font-extrabold text-red-800">{{ $stats['vencidas'] }}</p></div><div class="rounded-xl bg-amber-50 p-4"><p class="text-sm font-semibold text-amber-700">Necesidades sin compromiso</p><p class="text-3xl font-extrabold text-amber-800">{{ $stats['sin_compromiso'] }}</p></div><div class="rounded-xl bg-blue-50 p-4"><p class="text-sm font-semibold text-blue-700">Sin actualización en 30 días</p><p class="text-3xl font-extrabold text-blue-800">{{ $stats['sin_actualizar'] }}</p></div></div></section>
@endauth
<div class="grid lg:grid-cols-3 gap-5">
 <section class="ui-card p-5 lg:col-span-2"><div class="flex justify-between items-center"><div><h3 class="font-bold text-lg">Acciones por estado</h3><p class="text-sm text-slate-500">Distribución operativa del seguimiento</p></div><span class="ui-badge bg-emerald-100 text-emerald-700">{{ $stats['cumplidas'] }} completadas</span></div><div class="chart-box"><canvas id="estadoChart"></canvas></div></section>
 <section class="ui-card p-5"><h3 class="font-bold text-lg">Sectores de intervención</h3><p class="text-sm text-slate-500">Compromisos por sector temático</p><div class="chart-box"><canvas id="areaChart"></canvas></div></section>
</div>
</div></div>
@guest
<div x-data="{ open: {{ $errors->has('email') || $errors->has('password') ? 'true' : 'false' }} }" @open-login-modal.window="open=true" x-show="open" x-cloak class="login-modal" role="dialog" aria-modal="true" aria-labelledby="login-title" @keydown.escape.window="open=false">
 <div class="login-backdrop" @click="open=false"></div><div class="login-panel" @click.stop>
  <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wide text-emerald-700">Acceso a la plataforma</p><h2 id="login-title" class="mt-1 text-2xl font-extrabold text-slate-900">Iniciar sesión</h2><p class="mt-1 text-sm text-slate-500">Ingrese con las credenciales de su cuenta institucional.</p></div><button type="button" @click="open=false" class="ui-btn-secondary !px-3" aria-label="Cerrar">×</button></div>
  @if(session('status'))<div class="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('status') }}</div>@endif
  <form method="POST" action="{{ route('login') }}" class="mt-5 space-y-4">@csrf
   <div><x-input-label for="login-email" value="Correo electrónico"/><x-text-input id="login-email" class="mt-1 block w-full" type="email" name="email" :value="old('email')" required autofocus autocomplete="username"/><x-input-error :messages="$errors->get('email')" class="mt-2"/></div>
   <div><x-input-label for="login-password" value="Contraseña"/><x-text-input id="login-password" class="mt-1 block w-full" type="password" name="password" required autocomplete="current-password"/><x-input-error :messages="$errors->get('password')" class="mt-2"/></div>
   <label class="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" class="rounded border-gray-300 text-emerald-600 focus:ring-emerald-500" name="remember"> Recordar sesión</label>
   <div class="flex flex-wrap items-center justify-between gap-3">@if(Route::has('password.request'))<a class="text-sm font-semibold text-emerald-700 hover:underline" href="{{ route('password.request') }}">¿Olvidó su contraseña?</a>@endif<x-primary-button>Ingresar</x-primary-button></div>
  </form>
 </div>
</div>
@endguest
<div id="community-modal" class="modal-shell hidden" role="dialog" aria-modal="true" aria-labelledby="modal-title">
 <div class="modal-backdrop" data-close-modal></div><div class="modal-panel"><div class="modal-head"><div><p class="text-xs uppercase tracking-wide font-bold text-emerald-700">Ficha territorial completa</p><h2 id="modal-title" class="font-extrabold text-2xl"></h2><p id="modal-territory" class="text-sm text-slate-500"></p></div><button type="button" data-close-modal class="ui-btn-secondary !px-3" aria-label="Cerrar">✕</button></div><div id="modal-content" class="modal-body"></div></div>
</div>

@push('styles')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/><style>
[x-cloak]{display:none!important}.upcoming-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.75rem}.kpi-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:1rem}.chart-box{height:290px;margin-top:1rem}#map{height:580px;border-radius:12px}.community-label{background:#fff;border:1px solid #059669;color:#065f46;font-weight:700;box-shadow:0 1px 4px #0003}.marker-community{width:18px;height:18px;border-radius:50%;background:#059669;border:3px solid white;box-shadow:0 1px 5px #0008}.modal-shell,.login-modal{position:fixed;inset:0;z-index:2000;display:flex;justify-content:center;padding:1rem}.modal-shell{align-items:flex-start;overflow-y:auto;overscroll-behavior:contain}.login-modal{align-items:flex-start;overflow-y:auto;padding-top:2rem}.modal-shell.hidden{display:none}.modal-backdrop,.login-backdrop{position:fixed;inset:0;background:rgba(2,20,17,.68);backdrop-filter:blur(4px)}.modal-panel{position:relative;flex:none;width:min(1000px,96vw);height:auto;margin:auto 0;overflow:visible;background:#fff;border-radius:18px;box-shadow:0 30px 80px #0005;animation:pageEnter .28s ease-out}.login-panel{position:relative;flex:none;width:min(460px,96vw);max-height:calc(100dvh - 4rem);overflow-y:auto;background:#fff;border-radius:18px;padding:1.5rem;box-shadow:0 30px 80px #0005;animation:pageEnter .28s ease-out}.modal-head{padding:1.25rem 1.5rem;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;gap:1rem}.modal-body{padding:1.5rem;overflow:visible}.tree-need{border:1px solid #fde68a;background:#fffbeb;border-radius:12px;padding:1rem;margin-bottom:1rem}.tree-need:last-child{margin-bottom:0}.tree-commitment{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:.9rem;margin-top:.75rem}.tree-action{border-left:3px solid #10b981;padding:.55rem .75rem;margin-top:.6rem;background:#f8fafc;border-radius:0 8px 8px 0}
@media(max-width:1100px){.upcoming-grid{grid-template-columns:repeat(2,1fr)}.kpi-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:640px){.upcoming-grid{grid-template-columns:1fr}.kpi-grid{grid-template-columns:repeat(2,1fr)}#map{height:480px}.modal-shell,.login-modal{padding:.5rem}.modal-panel,.login-panel{width:100%;border-radius:14px}.login-panel{max-height:calc(100dvh - 1rem)}.modal-head,.modal-body{padding:1rem}.chart-box{height:250px}}
</style>@endpush
@push('scripts')
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>
const palette=['#10b981','#3b82f6','#f59e0b','#ef4444','#8b5cf6','#14b8a6','#64748b'];
new Chart(document.getElementById('estadoChart'),{type:'doughnut',data:{labels:@json($porEstado->keys()->map(fn($x)=>ucfirst(str_replace('_',' ',$x)))),datasets:[{data:@json($porEstado->values()),backgroundColor:palette,borderWidth:3,borderColor:'#fff'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});
new Chart(document.getElementById('areaChart'),{type:'bar',data:{labels:@json($porArea->keys()),datasets:[{label:'Compromisos',data:@json($porArea->values()),backgroundColor:'#059669',borderRadius:7}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{precision:0}},y:{grid:{display:false}}}}});
const base=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}),sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri'}),relief=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'}),map=L.map('map',{layers:[sat]}).setView([-22.02,-64.32],10);L.control.layers({'Predeterminado':base,'Satélite':sat,'Relieve':relief},null,{collapsed:true}).addTo(map);
const communityModal=document.getElementById('community-modal');
document.body.appendChild(communityModal);
const loginModal=document.querySelector('.login-modal');
if(loginModal)document.body.appendChild(loginModal);
const isPublic=@json($publico),communities=@json($mapaComunidades),layer=L.layerGroup().addTo(map),markers=[],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
communities.forEach(c=>{let lng=Number(c.longitud)+(c.nombre==='El Cajón'?.00025:0),needs=c.necesidades_relacionadas||[],commitments=needs.flatMap(n=>n.compromisos||[]),actions=commitments.flatMap(x=>x.acciones_ejecucion||[]),marker=L.marker([c.latitud,lng],{icon:L.divIcon({className:'',html:'<div class="marker-community"></div>',iconSize:[18,18]})}).bindTooltip(esc(c.nombre),{permanent:true,direction:'top',offset:[0,-9],className:'community-label'}).bindPopup('<b>'+esc(c.nombre)+'</b><br>'+needs.length+' necesidades · '+commitments.length+' compromisos · '+actions.length+' acciones<br><button onclick="openCommunity('+c.id+')" style="margin-top:8px;color:#047857;font-weight:700">Ver más información →</button>');markers.push({marker,c});});
function filterMap(){layer.clearLayers();let q=document.getElementById('map-search').value.toLowerCase(),t=document.getElementById('territory-filter').value,pts=[];markers.forEach(x=>{if((!q||x.c.nombre.toLowerCase().includes(q))&&(!t||x.c.territorio===t)){x.marker.addTo(layer);pts.push(x.marker.getLatLng())}});if(pts.length)map.fitBounds(pts,{padding:[35,35],maxZoom:13})}
document.getElementById('map-search').oninput=filterMap;document.getElementById('territory-filter').onchange=filterMap;filterMap();
window.openCommunity=id=>{const c=communities.find(x=>x.id===id),needs=c.necesidades_relacionadas||[];document.getElementById('modal-title').textContent=c.nombre;document.getElementById('modal-territory').textContent=c.territorio+' · '+c.latitud+', '+c.longitud;document.getElementById('modal-content').innerHTML=needs.length?needs.map(n=>'<section class="tree-need"><div><span class="ui-badge bg-amber-100 text-amber-800">'+esc(n.prioridad)+'</span><h3 class="font-bold mt-2">'+esc(n.titulo)+'</h3><p class="text-sm text-slate-600">'+esc(n.descripcion||'Sin descripción')+'</p></div>'+((n.compromisos||[]).map(c=>'<article class="tree-commitment"><p class="text-xs font-bold uppercase text-indigo-600">Compromiso</p><h4 class="font-bold">'+esc(c.titulo)+'</h4><p class="text-sm text-slate-500">'+esc(c.area)+' · '+esc(c.estado)+'</p>'+((c.acciones_ejecucion||[]).map(a=>'<div class="tree-action"><div class="flex flex-wrap justify-between gap-2"><b>'+esc(a.titulo)+'</b><span class="ui-badge bg-slate-100 text-slate-700">'+esc((a.estado||'sin estado').replaceAll('_',' '))+'</span></div><p class="text-sm text-slate-600">'+(isPublic?'Responsables disponibles al iniciar sesión':'Responsables: '+esc((a.responsables||[]).map(r=>r.nombre_completo).join(', ')||'Sin responsables'))+'</p></div>').join('')||'<p class="text-sm text-slate-500 mt-2">Sin acciones.</p>')+'</article>').join('')||'<p class="text-sm mt-2">Sin compromisos relacionados.</p>')+'</section>').join(''):'<p class="text-slate-500">Sin necesidades estructuradas.</p>';communityModal.scrollTop=0;communityModal.classList.remove('hidden');document.body.style.overflow='hidden'};
communityModal.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>{communityModal.classList.add('hidden');document.body.style.overflow=''});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!communityModal.classList.contains('hidden'))communityModal.querySelector('[data-close-modal]')?.click()});
</script>@endpush
</x-app-layout>
