@csrf
@php($a=$accion??null)
<div class="space-y-6">
 <section><h3 class="mb-4 border-b pb-2 text-lg font-bold">Compromiso y origen</h3><div class="grid gap-4 md:grid-cols-2">
  <div><x-input-label value="Título del compromiso"/><x-text-input name="titulo" class="mt-1 block w-full" :value="old('titulo',$a?->titulo)" required/><x-input-error :messages="$errors->get('titulo')" class="mt-2"/></div>
  <div><x-input-label value="Comunidades involucradas"/><div id="comunidades-necesidad" class="mt-1 min-h-[42px] rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-sm text-slate-600">Se completa desde la necesidad</div></div>
  <div><div class="flex items-center justify-between gap-2"><x-input-label value="Necesidad que origina el compromiso"/>@can('necesidades.create')<a href="{{ route('necesidades.create',['return_to'=>'compromisos.create']) }}" class="text-sm font-semibold text-emerald-700 hover:underline">+ Crear necesidad</a>@endcan</div><select id="necesidad_id" name="necesidad_id" class="mt-1 block w-full" required><option value="">Seleccione una necesidad</option>@foreach($necesidades as $n)<option value="{{ $n->id }}" data-comunidades="{{ $n->comunidades->pluck('nombre')->join(', ') }}" @selected(old('necesidad_id',$a?->necesidad_id??$necesidadSeleccionada??null)==$n->id)>{{ $n->titulo }} — {{ $n->comunidades->pluck('nombre')->join(', ') }}</option>@endforeach</select><x-input-error :messages="$errors->get('necesidad_id')" class="mt-2"/></div>
  <div><x-input-label value="Sector temático"/><select name="area" class="mt-1 block w-full" required><option value="">Seleccione un sector</option>@foreach($areas as $v)<option value="{{ $v }}" @selected(old('area',$a?->area)===$v)>{{ $v }}</option>@endforeach</select><x-input-error :messages="$errors->get('area')" class="mt-2"/></div>
  <div><x-input-label value="Prioridad"/><select name="prioridad" class="mt-1 block w-full"><option value="">Sin definir</option>@foreach(['baja','media','alta','critica'] as $v)<option value="{{ $v }}" @selected(old('prioridad',$a?->prioridad)===$v)>{{ ucfirst($v) }}</option>@endforeach</select></div>
  <div class="md:col-span-2"><x-input-label value="Descripción"/><textarea name="descripcion" rows="3" class="mt-1 block w-full">{{ old('descripcion',$a?->descripcion) }}</textarea></div>
 </div></section>
 <section><h3 class="mb-4 border-b pb-2 text-lg font-bold">Seguimiento</h3><div class="grid gap-4 md:grid-cols-3">
  <div><x-input-label value="Fecha del compromiso"/><x-text-input type="date" name="fecha_compromiso" class="mt-1 block w-full" :value="old('fecha_compromiso',$a?->fecha_compromiso?->format('Y-m-d'))"/></div>
  <div><x-input-label value="Fecha límite"/><x-text-input type="date" name="fecha_limite" class="mt-1 block w-full" :value="old('fecha_limite',$a?->fecha_limite?->format('Y-m-d'))"/></div>
  <div><x-input-label value="Estado"/><select name="estado" class="mt-1 block w-full">@foreach(['identificado'=>'Identificado','planificado'=>'Planificado','en_gestion'=>'En gestión','en_ejecucion'=>'En ejecución','cumplido'=>'Cumplido','suspendido'=>'Suspendido'] as $v=>$l)<option value="{{ $v }}" @selected(old('estado',$a?->estado??'identificado')===$v)>{{ $l }}</option>@endforeach</select></div>
  <div class="md:col-span-2"><x-input-label value="Próximo paso"/><textarea name="proximo_paso" rows="2" class="mt-1 block w-full">{{ old('proximo_paso',$a?->proximo_paso) }}</textarea></div>
  <div><x-input-label value="Fecha del próximo paso"/><x-text-input type="date" name="fecha_proximo_paso" class="mt-1 block w-full" :value="old('fecha_proximo_paso',$a?->fecha_proximo_paso?->format('Y-m-d'))"/></div>
  <div class="md:col-span-2"><x-input-label value="Problema o bloqueo"/><textarea name="problema_bloqueo" rows="2" class="mt-1 block w-full">{{ old('problema_bloqueo',$a?->problema_bloqueo) }}</textarea></div>
  <div><label class="mt-7 inline-flex items-center gap-2"><input type="hidden" name="requiere_decision" value="0"><input type="checkbox" name="requiere_decision" value="1" @checked(old('requiere_decision',$a?->requiere_decision))> Requiere decisión</label></div>
  <div class="md:col-span-2"><x-input-label value="Decisión requerida"/><textarea name="decision_requerida" rows="2" class="mt-1 block w-full">{{ old('decision_requerida',$a?->decision_requerida) }}</textarea></div>
  <div class="md:col-span-3"><x-input-label value="Resultado esperado"/><textarea name="resultado_esperado" rows="2" class="mt-1 block w-full">{{ old('resultado_esperado',$a?->resultado_esperado) }}</textarea></div>
 </div></section>
</div>
<div class="mt-6 flex gap-3"><x-primary-button>Guardar compromiso</x-primary-button><a href="{{ route('compromisos.index') }}" class="ui-btn-secondary">Cancelar</a></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const comunidades=document.getElementById('comunidades-necesidad'),necesidad=document.getElementById('necesidad_id');if(!comunidades||!necesidad)return;const sincronizar=()=>{comunidades.textContent=necesidad.selectedOptions[0]?.dataset.comunidades||'Seleccione una necesidad'};necesidad.addEventListener('change',sincronizar);sincronizar()});</script>
