@csrf
<div class="grid md:grid-cols-2 gap-5">
 <div><x-input-label for="nombre" value="Nombre"/><x-text-input id="nombre" name="nombre" class="mt-1 block w-full" :value="old('nombre',$comunidad->nombre ?? '')" required/><x-input-error :messages="$errors->get('nombre')" class="mt-2"/></div>
 <div><x-input-label for="territorio" value="Territorio"/><select id="territorio" name="territorio" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm"><option value="">Seleccione</option>@foreach(['Tariquía','Chiquiacá - Salinas','La Planchada - El Cajón'] as $t)<option @selected(old('territorio',$comunidad->territorio ?? '')===$t)>{{ $t }}</option>@endforeach</select></div>
 <div><x-input-label for="latitud" value="Latitud"/><x-text-input id="latitud" name="latitud" type="number" step="any" class="mt-1 block w-full" :value="old('latitud',$comunidad->latitud ?? '')" required/><x-input-error :messages="$errors->get('latitud')" class="mt-2"/></div>
 <div><x-input-label for="longitud" value="Longitud"/><x-text-input id="longitud" name="longitud" type="number" step="any" class="mt-1 block w-full" :value="old('longitud',$comunidad->longitud ?? '')" required/><x-input-error :messages="$errors->get('longitud')" class="mt-2"/></div>
 <div class="md:col-span-2"><p class="text-sm text-gray-500 mb-2">Haz clic en el mapa o arrastra el marcador para ajustar la ubicación.</p><div id="picker-map" class="rounded-lg border" style="height:360px"></div></div>
</div>
<div class="mt-6 flex gap-3"><x-primary-button>Guardar comunidad</x-primary-button><a href="{{ route('comunidades.index') }}" class="px-4 py-2 border rounded-md">Cancelar</a></div>
@push('styles')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>@endpush
@push('scripts')<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{const a=document.getElementById('latitud'),o=document.getElementById('longitud');let lat=parseFloat(a.value)||-22.02,lng=parseFloat(o.value)||-64.32;const base=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}),sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}),relief=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'});const m=L.map('picker-map',{layers:[base]}).setView([lat,lng],10);L.control.layers({'Predeterminado':base,'Satélite':sat,'Relieve':relief},null,{collapsed:false}).addTo(m);const k=L.marker([lat,lng],{draggable:true}).addTo(m);const set=p=>{a.value=p.lat.toFixed(7);o.value=p.lng.toFixed(7);k.setLatLng(p)};m.on('click',e=>set(e.latlng));k.on('dragend',()=>set(k.getLatLng()));});
</script>@endpush
