<div id="report-log-drawer" class="report-log-shell hidden" aria-hidden="true">
 <button type="button" class="report-log-backdrop" data-log-close aria-label="Cerrar bitácora"></button>
 <aside class="report-log-panel" role="dialog" aria-modal="true" aria-labelledby="report-log-title">
  <header class="report-log-head"><div><p class="text-xs font-bold uppercase tracking-wide text-emerald-700">Bitácora de acción</p><h2 id="report-log-title" class="text-xl font-extrabold text-slate-900">Bitácora</h2><p id="report-log-meta" class="mt-1 text-sm text-slate-500"></p></div><button type="button" class="report-log-close" data-log-close aria-label="Cerrar">×</button></header>
  <div id="report-log-body" class="report-log-body"></div>
  <footer class="border-t bg-white p-4"><a id="report-log-link" href="#" class="ui-btn-primary w-full justify-center">Abrir bitácora completa</a></footer>
 </aside>
</div>
<div id="report-photo-preview" class="report-photo-shell hidden" aria-hidden="true"><button type="button" class="report-photo-backdrop" data-photo-close aria-label="Cerrar fotografía"></button><figure class="report-photo-frame"><button type="button" class="report-photo-close" data-photo-close aria-label="Cerrar">×</button><img id="report-photo-image" src="" alt=""><figcaption id="report-photo-caption"></figcaption></figure></div>
@push('styles')
<style>
.report-log-shell,.report-photo-shell{position:fixed;inset:0;z-index:2200}.report-log-shell.hidden,.report-photo-shell.hidden{display:none}.report-log-backdrop,.report-photo-backdrop{position:absolute;inset:0;width:100%;border:0;background:#03171399;backdrop-filter:blur(3px)}.report-log-panel{position:absolute;right:0;top:0;display:flex;height:100%;width:min(620px,94vw);flex-direction:column;background:#f8fafc;box-shadow:-18px 0 55px #0004;animation:reportDrawerIn .25s ease-out}.report-log-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;border-bottom:1px solid #e2e8f0;background:#fff;padding:1.25rem}.report-log-close,.report-photo-close{display:flex;height:40px;width:40px;flex:none;align-items:center;justify-content:center;border:1px solid #cbd5e1;border-radius:.7rem;background:#fff;color:#475569;font-size:1.6rem;line-height:1}.report-log-body{flex:1;overflow-y:auto;padding:1.25rem}.report-log-entry{position:relative;margin-left:.4rem;border-left:2px solid #6ee7b7;padding:0 0 1.35rem 1.25rem}.report-log-entry::before{position:absolute;left:-7px;top:4px;height:12px;width:12px;border:2px solid #fff;border-radius:999px;background:#059669;box-shadow:0 0 0 1px #6ee7b7;content:""}.report-log-entry:last-child{padding-bottom:0}.report-log-photos{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.5rem;margin-top:.75rem}.report-log-photo{overflow:hidden;border:1px solid #dbe5e1;border-radius:.65rem;background:#fff}.report-log-photo img{height:92px;width:100%;object-fit:cover;transition:transform .2s}.report-log-photo:hover img{transform:scale(1.05)}.report-log-photo span{display:block;overflow:hidden;padding:.3rem .45rem;text-overflow:ellipsis;white-space:nowrap;font-size:.65rem;color:#64748b}.report-photo-shell{z-index:2300;display:flex;align-items:center;justify-content:center;padding:1rem}.report-photo-frame{position:relative;z-index:1;max-height:94vh;max-width:min(1100px,96vw);overflow:hidden;border-radius:1rem;background:#0f172a;box-shadow:0 25px 70px #0008}.report-photo-frame img{display:block;max-height:85vh;max-width:100%;object-fit:contain}.report-photo-frame figcaption{padding:.65rem 1rem;color:#fff;font-size:.8rem}.report-photo-close{position:absolute;right:.75rem;top:.75rem;border-color:#ffffff55;background:#0f172acc;color:#fff}@keyframes reportDrawerIn{from{opacity:.4;transform:translateX(40px)}to{opacity:1;transform:none}}@media(max-width:640px){.report-log-panel{top:auto;bottom:0;height:min(88dvh,760px);width:100%;border-radius:1rem 1rem 0 0}.report-log-photos{grid-template-columns:repeat(2,minmax(0,1fr))}}@media print{.report-log-shell,.report-photo-shell,.js-report-log{display:none!important}}
.report-log-panel{height:100vh;height:100dvh}.report-log-body{min-height:0}
</style>
@endpush
@push('scripts')
<script>
(()=>{const drawer=document.getElementById('report-log-drawer'),body=document.getElementById('report-log-body'),title=document.getElementById('report-log-title'),meta=document.getElementById('report-log-meta'),link=document.getElementById('report-log-link'),preview=document.getElementById('report-photo-preview'),previewImage=document.getElementById('report-photo-image'),previewCaption=document.getElementById('report-photo-caption');if(!drawer)return;
 document.body.append(drawer,preview);
 const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
 const openDrawer=async button=>{drawer.classList.remove('hidden');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';title.textContent=button.dataset.title||'Bitácora';meta.textContent='Cargando registros…';body.innerHTML='<div class="rounded-xl border bg-white p-8 text-center text-slate-500">Cargando bitácora…</div>';
  try{const response=await fetch(button.dataset.url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();title.textContent=data.titulo;meta.textContent=(data.registros.length+' registro(s) · '+data.avance+'% de avance · '+String(data.estado).replaceAll('_',' '));link.href=data.url;body.innerHTML=data.registros.map(record=>'<article class="report-log-entry"><div class="flex flex-wrap items-start justify-between gap-2"><div><b class="text-sm text-slate-800">'+esc(record.fecha_hora)+'</b><small class="block text-slate-500">'+esc(record.usuario)+'</small></div>'+(record.avance!==null?'<span class="ui-badge bg-emerald-100 text-emerald-700">'+record.avance+'%</span>':'')+'</div><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-700">'+esc(record.descripcion)+'</p>'+(record.fotos.length?'<div class="report-log-photos">'+record.fotos.map(photo=>'<button type="button" class="report-log-photo js-report-photo" data-src="'+esc(photo.url)+'" data-caption="'+esc(photo.nombre)+'"><img src="'+esc(photo.url)+'" alt="'+esc(photo.nombre)+'" loading="lazy"><span>'+esc(photo.nombre)+'</span></button>').join('')+'</div>':'')+'</article>').join('')||'<div class="rounded-xl border border-dashed bg-white p-8 text-center text-slate-500">Esta acción aún no tiene registros de bitácora.</div>'}catch(error){meta.textContent='';body.innerHTML='<div class="rounded-xl border border-red-200 bg-red-50 p-6 text-center text-red-700">No se pudo cargar la bitácora.</div>'}};
 const closeDrawer=()=>{drawer.classList.add('hidden');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''};const closePhoto=()=>{preview.classList.add('hidden');preview.setAttribute('aria-hidden','true');previewImage.src=''};
 document.addEventListener('click',event=>{const logButton=event.target.closest('.js-report-log');if(logButton){event.preventDefault();openDrawer(logButton);return}const photo=event.target.closest('.js-report-photo');if(photo){previewImage.src=photo.dataset.src;previewImage.alt=photo.dataset.caption;previewCaption.textContent=photo.dataset.caption;preview.classList.remove('hidden');preview.setAttribute('aria-hidden','false')}});drawer.querySelectorAll('[data-log-close]').forEach(element=>element.addEventListener('click',closeDrawer));preview.querySelectorAll('[data-photo-close]').forEach(element=>element.addEventListener('click',closePhoto));document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!preview.classList.contains('hidden'))closePhoto();else if(!drawer.classList.contains('hidden'))closeDrawer()}});
})();
</script>
@endpush
