<x-app-layout>
 <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-xl">Acciones</h2><p class="text-sm text-slate-500">Tareas concretas generadas desde las demandas.</p></div>@can('acciones.create')<a href="{{ route('acciones.create') }}" class="ui-btn-primary">+ Nueva acción</a>@endcan</div></x-slot>
 <div class="py-6"><div class="max-w-7xl mx-auto px-4 space-y-4">
 @if(session('success'))<div class="bg-emerald-100 text-emerald-800 p-3 rounded">{{ session('success') }}</div>@endif
 <div class="ui-toolbar"><form class="flex flex-1 flex-wrap gap-3"><input name="buscar" value="{{ request('buscar') }}" placeholder="Buscar acción" class="min-w-48 flex-1"><select name="estado"><option value="">Todos los estados</option>@foreach(['pendiente'=>'Pendiente','en_ejecucion'=>'En ejecución','completada'=>'Completada','bloqueada'=>'Bloqueada'] as $value=>$label)<option value="{{ $value }}" @selected(request('estado')===$value)>{{ $label }}</option>@endforeach</select><button class="ui-btn-secondary !bg-slate-800 !text-white">Filtrar</button></form></div>
 <div class="ui-table-shell overflow-x-auto"><table class="w-full min-w-[900px] text-sm"><thead><tr><th class="p-3 text-left">Acción</th><th class="p-3 text-left">Origen</th><th class="p-3 text-left">Responsables</th><th class="p-3 text-left">Estado</th><th class="p-3 text-center">Gestión</th></tr></thead><tbody>
 @forelse($acciones as $accion)<tr class="border-t align-top"><td class="p-3"><strong>{{ $accion->titulo }}</strong><small class="mt-1 block text-slate-500">{{ $accion->fecha_limite?->format('d/m/Y')??'Sin fecha límite' }}</small></td><td class="p-3"><a class="font-semibold text-emerald-700 hover:underline" href="{{ route('demandas.show',$accion->demanda) }}">{{ $accion->demanda?->titulo }}</a><small class="mt-1 block text-slate-500">{{ $accion->demanda?->comunidades?->pluck('nombre')->join(', ')??'Sin comunidad' }}</small></td><td class="p-3">@forelse($accion->responsables as $responsable)<span class="ui-badge mb-1 mr-1 bg-indigo-100 text-indigo-700">{{ $responsable->nombre_completo }}</span>@empty<span class="text-slate-500">Sin responsables</span>@endforelse</td><td class="p-3"><span class="ui-badge bg-slate-100 text-slate-700">{{ ucfirst(str_replace('_',' ',$accion->estado)) }}</span></td><td class="p-3"><div class="flex justify-center gap-2">@can('acciones.edit')<a href="{{ route('acciones.edit',$accion) }}" class="ui-btn-info !px-3 !py-2">Editar</a>@endcan @can('acciones.delete')<form method="POST" action="{{ route('acciones.destroy',$accion) }}" onsubmit="return confirm('¿Eliminar esta acción?')">@csrf @method('DELETE')<button class="ui-btn-danger !px-3 !py-2">Eliminar</button></form>@endcan</div></td></tr>
 @empty<tr><td colspan="5" class="p-8 text-center text-slate-500">No hay acciones registradas.</td></tr>@endforelse
 </tbody></table><div class="border-t p-4">{{ $acciones->links() }}</div></div>
 </div></div>
</x-app-layout>

