<x-app-layout>
 <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-xl">Administración de usuarios</h2><p class="text-sm text-slate-500">Cuentas, roles y acceso institucional.</p></div>@can('roles.view')<a href="{{ route('admin.roles.index') }}" class="ui-btn-secondary">Roles y permisos</a>@endcan</div></x-slot>
 <div class="py-6"><div class="max-w-7xl mx-auto px-4 space-y-4">
 @if(session('success'))<div class="bg-emerald-100 text-emerald-800 p-3 rounded">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="rounded border border-red-200 bg-red-50 p-3 text-red-700">{{ $errors->first() }}</div>@endif
 <div class="ui-toolbar"><form class="flex flex-1 flex-wrap gap-3"><input name="buscar" value="{{ request('buscar') }}" placeholder="Buscar por nombre o correo" class="min-w-56 flex-1"><button class="ui-btn-secondary !bg-slate-800 !text-white">Buscar</button></form>@can('users.create')<a href="{{ route('admin.users.create') }}" class="ui-btn-primary">+ Crear usuario</a>@endcan</div>
 <div class="ui-table-shell overflow-x-auto"><table class="w-full min-w-[850px] text-sm"><thead><tr><th class="p-3 text-left">Usuario</th><th class="p-3 text-left">Rol</th><th class="p-3 text-center">Estado</th><th class="p-3 text-left">Credenciales</th><th class="p-3 text-center">Acciones</th></tr></thead><tbody>
 @forelse($users as $user)<tr class="border-t"><td class="p-3"><strong class="block">{{ $user->name }}</strong><span class="text-slate-500">{{ $user->email }}</span></td><td class="p-3"><span class="ui-badge bg-indigo-100 text-indigo-700">{{ ucfirst($user->roles->first()?->name??'Sin rol') }}</span></td><td class="p-3 text-center"><span class="ui-badge {{ $user->is_active?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600' }}">{{ $user->is_active?'Activo':'Inactivo' }}</span>@if($user->must_change_password)<small class="mt-1 block text-amber-700">Clave temporal</small>@endif</td><td class="p-3 text-slate-600">{{ $user->credentials_sent_at?->format('d/m/Y H:i')??'Registro anterior' }}</td><td class="p-3"><div class="flex flex-wrap justify-center gap-2">
 @can('users.edit')<a href="{{ route('admin.users.edit',$user) }}" class="ui-btn-info !px-3 !py-2">Editar</a><form method="POST" action="{{ route('admin.users.resend',$user) }}" onsubmit="return confirm('Se cambiará la contraseña actual. ¿Continuar?')">@csrf<button class="ui-btn-secondary !px-3 !py-2">Reenviar acceso</button></form>@endcan
 @can('users.delete')@if(!$user->is(auth()->user()))<form method="POST" action="{{ route('admin.users.destroy',$user) }}" onsubmit="return confirm('¿Eliminar este usuario?')">@csrf @method('DELETE')<button class="ui-btn-danger !px-3 !py-2">Eliminar</button></form>@endif @endcan
 </div></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">No se encontraron usuarios.</td></tr>@endforelse
 </tbody></table><div class="border-t p-4">{{ $users->links() }}</div></div>
 </div></div>
</x-app-layout>
